name: 360T7-ipk

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - run: go version

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Clone source code
      run: |
        df -hT $PWD
        wget -q https://downloads.openwrt.org/releases/23.05.0/targets/mediatek/filogic/openwrt-sdk-23.05.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        tar -xJf openwrt-sdk-23.05.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz

    - name: add feeds
      run: |
        cd openwrt-sdk-23.05.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64
        echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main" >> "feeds.conf.default"
        echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main" >> "feeds.conf.default"

    - name: Update feeds
      run: cd openwrt-sdk-23.05.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64 && ./scripts/feeds update -a

    - name: 替换GO版本
      run: cd openwrt-sdk-23.05.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64 && git clone --depth 1 https://github.com/immortalwrt/packages.git package/immortalwrt-packages && rm -rf ./feeds/packages/lang/golang && \cp -rf ./package/immortalwrt-packages/lang/golang ./feeds/packages/lang/ && rm -rf ./package/immortalwrt-packages

    - name: passwall
      run: |
        cd openwrt-sdk-23.05.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64
        ./scripts/feeds install -a -f -p passwall_packages
        ./scripts/feeds install luci-app-passwall
        ./scripts/feeds install luci-base

    #- name: 【步骤】
      #run: echo "【输入q 然后cd openwrt-sdk-23.05.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64 && make menuconfig 结束sudo touch /continue】"
    #- name: Setup tmate session # https://github.com/mxschmitt/action-tmate https://github.com/marketplace/actions/debugging-with-ssh
      #uses: mxschmitt/action-tmate@v3
      #timeout-minutes: 30

    - name: build
      run: |
        cd openwrt-sdk-23.05.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64
        \cp -f $GITHUB_WORKSPACE/config/ipk.config .config
        make package/luci-base/compile V=99
        make defconfig
        make download -j8 V=s
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        # 替换规则
        find . -type f -name "rule.lua"
        sed -i 's|https://fastly.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat|https://github.com/najloa/geoip/releases/latest/download/geoip.dat|g' ./feeds/passwall/luci-app-passwall/luasrc/model/cbi/passwall/client/rule.lua
        sed -i 's|https://fastly.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat|https://github.com/najloa/geoip/releases/latest/download/geosite.dat|g' ./feeds/passwall/luci-app-passwall/luasrc/model/cbi/passwall/client/rule.lua
        sed -i 's|translate("Loyalsoldier/geosite")|translate("najloa/geosite")|g' ./feeds/passwall/luci-app-passwall/luasrc/model/cbi/passwall/client/rule.lua
        sed -i 's|translate("Loyalsoldier/geoip")|translate("najloa/geoip")|g' ./feeds/passwall/luci-app-passwall/luasrc/model/cbi/passwall/client/rule.lua
        sed -i 's|translate("Loyalsoldier/v2ray-rules-dat")|translate("najloa/v2ray-rules-dat")|g' ./feeds/passwall/luci-app-passwall/luasrc/model/cbi/passwall/client/rule.lua
        sed -i 's|https://fastly.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/gfw.txt|https://raw.githubusercontent.com/najloa/geoip/rules/proxy-list.txt|g' ./feeds/passwall/luci-app-passwall/luasrc/model/cbi/passwall/client/rule.lua
        sed -i 's|https://fastly.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat|https://github.com/najloa/geoip/releases/latest/download/geoip.dat|g' ./feeds/passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
        sed -i 's|https://fastly.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat|https://github.com/najloa/geoip/releases/latest/download/geosite.dat|g' ./feeds/passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
        sed -i 's|https://fastly.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/gfw.txt|https://raw.githubusercontent.com/najloa/geoip/rules/proxy-list.txt|g' ./feeds/passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
        sed -i 's|https://fastly.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat|https://github.com/najloa/geoip/releases/latest/download/geoip.dat|g' ./feeds/passwall/luci-app-passwall/root/usr/share/passwall/rule_update.lua
        sed -i 's|https://fastly.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat|https://github.com/najloa/geoip/releases/latest/download/geosite.dat|g' ./feeds/passwall/luci-app-passwall/root/usr/share/passwall/rule_update.lua
        sed -i 's|https://fastly.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/gfw.txt|https://raw.githubusercontent.com/najloa/geoip/rules/proxy-list.txt|g' ./feeds/passwall/luci-app-passwall/root/usr/share/passwall/rule_update.lua
        sed -i 's|local excluded_domain = {[^}]*}|local excluded_domain = {}|g' ./feeds/passwall/luci-app-passwall/root/usr/share/passwall/rule_update.lua
        make package/luci-app-passwall/compile V=99
        #make package/geoview/compile V=99
        #make package/sing-box/compile V=99
        #make package/xray-core/compile V=99
        #make package/coreutils/compile V=99
        #make package/coreutils-base64/compile V=99
        #make package/coreutils-nohup/compile V=99
        #make package/chinadns-ng/compile V=99
        #make package/dns2socks/compile V=99
        #make package/ip-full/compile V=99
        #make package/libuci-lua/compile V=99
        #make package/microsocks/compile V=99
        #make package/tcping/compile V=99
        #make package/luci-lua-runtime/compile V=99

    - name: Locate .ipk
      run: |
        mkdir -p ipk-out
        find ./ -type f -name '*passwall*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*geoview*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*sing-box*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*coreutils_*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*coreutils-base64*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*coreutils-nohup*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*chinadns-ng*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*dns2socks*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*ipt2socks*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*ip-full*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*libbpf*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*libnl-tiny*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*libuci-lua*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*microsocks*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*tcping*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*luci-lua-runtime*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*ucode-mod-lua*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*iptables-zz-legacy*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*unzip*.ipk' -exec cp {} ipk-out/ \;

    - name: Upload directory
      uses: actions/upload-artifact@main
      with:
        name: ipk
        path: ipk-out/

    - name: config
      run: |
        cd openwrt-sdk-23.05.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64
        cp -f .config ipk.config

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: config
        path: openwrt-sdk-23.05.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/ipk.config

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 0
