name: 360T7-21.02-config

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Initialization environment
      run: sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'

    - name: download
      run: git clone --depth=1 https://github.com/hanwckf/immortalwrt-mt798x.git

    - name: update
      run: cd immortalwrt-mt798x && ./scripts/feeds update -a

    - name: install
      run: cd immortalwrt-mt798x && ./scripts/feeds install -a

    - name: defconfig
      run: cd immortalwrt-mt798x && cp -f defconfig/mt7981-ax3000.config .config

    - name: passwall
      run: |
        cd immortalwrt-mt798x
        # 移除 openwrt feeds 自带的核心库
        rm -rf feeds/packages/net/{xray-core,v2ray-geodata,sing-box,chinadns-ng,dns2socks,hysteria,ipt2socks,microsocks,naiveproxy,shadowsocks-rust,shadowsocksr-libev,simple-obfs,tcping,v2ray-plugin,xray-plugin,geoview,shadow-tls}
        git clone https://github.com/Openwrt-Passwall/openwrt-passwall-packages package/passwall-packages
        # 移除 openwrt feeds 过时的luci版本
        rm -rf feeds/luci/applications/luci-app-passwall
        git clone https://github.com/Openwrt-Passwall/openwrt-passwall package/passwall-luci

    #【输入q 然后cd immortalwrt-mt798x && make menuconfig】【结束sudo touch /continue】【如需多个配置install -Dp .config ./publish/360T7-21.02-.config && cp -f defconfig/mt7981-ax3000.config .config】【https://github.com/mxschmitt/action-tmate】
    
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 35

    - name: cp config
      run: |
        cd immortalwrt-mt798x
        install -Dp .config ./publish/360T7-21.02.config

    - name: Sync publish to repo config folder
      run: |
        mkdir -p config
        cp -rf immortalwrt-mt798x/publish/* config/

    - name: Commit and push configs
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add config/
        git commit -m "update configs (publish sync)" || echo "No changes to commit"
        git push

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        keep_minimum_runs: 2
        delete_workflow_pattern: 360T7-21.02-config
