name: 360T7-2410-config

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      run: sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'

    - name: download
      run: git clone -b openwrt-24.10-6.6 https://github.com/padavanonly/immortalwrt-mt798x-6.6

    - name: update
      run: cd immortalwrt-mt798x-6.6 && ./scripts/feeds update -a

    - name: install
      run: cd immortalwrt-mt798x-6.6 && ./scripts/feeds install -a

    - name: Replace
      run: |
        cd immortalwrt-mt798x-6.6
        cp -f defconfig/mt7981-ax3000.config .config
        # 移除 openwrt feeds 自带的核心库
        rm -rf feeds/packages/net/{xray-core,v2ray-geodata,sing-box,chinadns-ng,dns2socks,hysteria,ipt2socks,microsocks,naiveproxy,shadowsocks-rust,shadowsocksr-libev,simple-obfs,tcping,v2ray-plugin,xray-plugin,geoview,shadow-tls}
        git clone https://github.com/Openwrt-Passwall/openwrt-passwall-packages package/passwall-packages
        # 移除 openwrt feeds 过时的luci版本
        rm -rf feeds/luci/applications/luci-app-passwall
        git clone https://github.com/Openwrt-Passwall/openwrt-passwall package/passwall-luci

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 20

    #【步骤】输入q 然后cd immortalwrt-mt798x-6.6 && make menuconfig 结束sudo touch /continue

    - name: config
      run: |
        cd immortalwrt-mt798x-6.6
        cp .config $GITHUB_WORKSPACE/360T7_2410.config

    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: ${{ github.run_number }}
        path: 360T7_2410.config

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 0
        delete_workflow_pattern: 360T7-2410-config
