name: 360T7-2410-config

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Cache APT
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-v1

    - name: Initialization environment
      run: |
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
          g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
          libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
          libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
          ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
          python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
          upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd

    - name: download
      run: git clone -b openwrt-24.10-6.6 --single-branch --filter=blob:none https://github.com/padavanonly/immortalwrt-mt798x-6.6 immortalwrt-mt798x

    - name: update
      run: cd immortalwrt-mt798x && ./scripts/feeds update -a

    - name: install
      run: cd immortalwrt-mt798x && ./scripts/feeds install -a

    - name: cp
      run: cd immortalwrt-mt798x && cp -f defconfig/mt7981-ax3000.config .config

    - name: 【步骤】
      run: echo "【输入q 然后cd immortalwrt-mt798x && make menuconfig 结束sudo touch /continue】"
    - name: Setup tmate session # https://github.com/mxschmitt/action-tmate https://github.com/marketplace/actions/debugging-with-ssh
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 45

    - name: config
      run: |
        cd immortalwrt-mt798x
        cp -f .config 360T7_2410.config

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: 360T7_2410
        path: immortalwrt-mt798x/360T7_2410.config

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 30
        keep_minimum_runs: 6
