#name: 360T7-ipk

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - run: go version

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Clone source code
      run: |
        df -hT $PWD
        git clone --depth=1 https://github.com/hanwckf/immortalwrt-mt798x.git

    - name: add feeds
      run: |
        cd immortalwrt-mt798x
        echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main" >> "feeds.conf.default"
        echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main" >> "feeds.conf.default"

    - name: Update feeds
      run: cd immortalwrt-mt798x && ./scripts/feeds update -a

    - name: del
      run: |
        cd immortalwrt-mt798x
        find . -type d -name "sing-box"
        find . -type d -name "xray-core"
        rm -rf ./feeds/luci/applications/luci-app-passwall
        rm -rf ./feeds/packages/net/chinadns-ng
        rm -rf ./feeds/packages/net/dns2socks
        rm -rf ./feeds/packages/net/ipt2socks
        rm -rf ./feeds/packages/net/microsocks
        rm -rf ./feeds/packages/net/tcping
        rm -rf ./feeds/packages/net/sing-box
        rm -rf ./feeds/packages/net/xray-core
        ./scripts/feeds install -f -p passwall luci-app-passwall
        ./scripts/feeds install -f -p passwall_packages chinadns-ng
        ./scripts/feeds install -f -p passwall_packages dns2socks
        ./scripts/feeds install -f -p passwall_packages ipt2socks
        ./scripts/feeds install -f -p passwall_packages microsocks
        ./scripts/feeds install -f -p passwall_packages tcping
        ./scripts/feeds install -f -p passwall_packages sing-box
        ./scripts/feeds install -f -p passwall_packages xray-core
        find . -type f -name "rule.lua"
        sed -i 's|https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat|https://github.com/najloa/geoip/releases/latest/download/geoip.dat|g' ./feeds/passwall/luci-app-passwall/luasrc/model/cbi/passwall/client/rule.lua
        sed -i 's|https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat|https://github.com/najloa/geoip/releases/latest/download/geosite.dat|g' ./feeds/passwall/luci-app-passwall/luasrc/model/cbi/passwall/client/rule.lua
        sed -i 's|https://fastly.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/gfw.txt|https://github.com/najloa/geoip/releases/latest/download/proxy-list.txt|g' ./feeds/passwall/luci-app-passwall/luasrc/model/cbi/passwall/client/rule.lua
        sed -i 's|https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat|https://github.com/najloa/geoip/releases/latest/download/geoip.dat|g' ./feeds/passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
        sed -i 's|https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat|https://github.com/najloa/geoip/releases/latest/download/geosite.dat|g' ./feeds/passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
        sed -i 's|https://fastly.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/gfw.txt|https://github.com/najloa/geoip/releases/latest/download/proxy-list.txt|g' ./feeds/passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
        sed -i 's|https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat|https://github.com/najloa/geoip/releases/latest/download/geoip.dat|g' ./feeds/passwall/luci-app-passwall/root/usr/share/passwall/rule_update.lua
        sed -i 's|https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat|https://github.com/najloa/geoip/releases/latest/download/geosite.dat|g' ./feeds/passwall/luci-app-passwall/root/usr/share/passwall/rule_update.lua
        sed -i 's|https://fastly.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/gfw.txt|https://github.com/najloa/geoip/releases/latest/download/proxy-list.txt|g' ./feeds/passwall/luci-app-passwall/root/usr/share/passwall/rule_update.lua
        sed -i 's|local excluded_domain = {[^}]*}|local excluded_domain = {}|g' ./feeds/passwall/luci-app-passwall/root/usr/share/passwall/rule_update.lua

    - name: install
      run: cd immortalwrt-mt798x && ./scripts/feeds install -a
        
    - name: 替换GO版本
      run: cd immortalwrt-mt798x && git clone --depth 1 https://github.com/immortalwrt/packages.git package/immortalwrt-packages && rm -rf ./feeds/packages/lang/golang && \cp -rf ./package/immortalwrt-packages/lang/golang ./feeds/packages/lang/ && rm -rf ./package/immortalwrt-packages

    #- name: 【步骤】
      #run: echo "【输入q 然后cd openwrt-sdk-23.05.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64 && make menuconfig 结束sudo touch /continue】"
    #- name: Setup tmate session # https://github.com/mxschmitt/action-tmate https://github.com/marketplace/actions/debugging-with-ssh
      #uses: mxschmitt/action-tmate@v3
      #timeout-minutes: 30

    - name: build
      run: |
        cd immortalwrt-mt798x
        \cp -f $GITHUB_WORKSPACE/config/ipk.config .config
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        make -j$(nproc) || make -j1 || make -j1 V=s

    - name: Locate .ipk
      run: |
        mkdir -p ipk-out
        find ./ -type f -name '*passwall*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*geoview*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*chinadns-ng*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*sing-box*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*xray-core*.ipk' -exec cp {} ipk-out/ \;

    - name: Upload directory
      uses: actions/upload-artifact@main
      with:
        name: ipk
        path: ipk-out/

    - name: config
      run: |
        cd immortalwrt-mt798x
        cp -f .config ipk.config

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: config
        path: immortalwrt-mt798x/ipk.config

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 0
