name: 360T7-21.02-ipk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Initialization environment
      run: sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'

    - name: Download OpenWrt SDK 21.02
      run: |
        wget -O sdk.tar.xz https://archive.openwrt.org/releases/21.02.7/targets/x86/64/openwrt-sdk-21.02.7-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        mkdir sdk
        tar -xJf sdk.tar.xz -C sdk --strip-components=1

    - name: Setup feeds
      run: |
        cd sdk

        sed -i \
            -e 's|git\.openwrt\.org/feed|github.com/openwrt|g' \
            -e 's|git\.openwrt\.org/project|github.com/openwrt|g' \
            -e 's|git\.openwrt\.org/openwrt|github.com/openwrt|g' \
            "feeds.conf.default"

        cat > feeds.tmp <<'EOF'
        src-git passwall_packages https://github.com/Openwrt-Passwall/openwrt-passwall-packages.git;main
        src-git passwall https://github.com/Openwrt-Passwall/openwrt-passwall.git;main
        EOF
        cat feeds.conf.default >> feeds.tmp
        mv feeds.tmp feeds.conf.default

        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Compile
      run: |
        cd sdk
        echo "CONFIG_ALL_NONSHARED=n" > .config
        echo "CONFIG_ALL_KMODS=n" >> .config
        echo "CONFIG_ALL=n" >> .config
        echo "CONFIG_AUTOREMOVE=n" >> .config
        echo "CONFIG_LUCI_LANG_zh_Hans=y" >> .config
        echo "CONFIG_PACKAGE_luci-app-passwall=m" >> .config
        echo "CONFIG_PACKAGE_geoview=m" >> .config
        echo "CONFIG_PACKAGE_sing-box=m" >> .config
        echo "CONFIG_PACKAGE_xray-core=m" >> .config
        make defconfig
        echo "make package/luci-app-passwall/{clean,compile} -j$(nproc)"
        make package/luci-app-passwall/{clean,compile} -j$(nproc) V=s
        echo "make package/geoview/{clean,compile} -j$(nproc)"
        make package/geoview/{clean,compile} -j$(nproc) V=s
        echo "make package/sing-box/{clean,compile} -j$(nproc)"
        make package/sing-box/{clean,compile} -j$(nproc) V=s
        echo "make package/xray-core/{clean,compile} -j$(nproc)"
        make package/xray-core/{clean,compile} -j$(nproc) V=s

    - name: Generate build date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

    - name: IPK files
      run: |
        mkdir ipk-out
        find ./ -type f -name '*passwall*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*geoview*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*xray*.ipk' -exec cp {} ipk-out/ \;
        find ./ -type f -name '*sing-box*.ipk' -exec cp {} ipk-out/ \;

    - name: Pack IPK files
      run: |
        cd ipk-out
        zip -r ../21.02-ipk.zip .

    - name: Upload to release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: 21.02
        overwrite: true
        files: 21.02-ipk.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 0
        delete_workflow_pattern: 360T7-21.02-ipk
