#name: 360T7-ipk

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - run: go version

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Clone source code
      run: |
        df -hT $PWD
        git clone --depth=1 https://github.com/hanwckf/immortalwrt-mt798x.git

    - name: Update feeds
      run: cd immortalwrt-mt798x && ./scripts/feeds update -a

    - name: passwall
      run: |
        cd immortalwrt-mt798x
        # 移除 openwrt feeds 自带的核心库
        rm -rf feeds/packages/net/{xray-core,v2ray-geodata,sing-box,chinadns-ng,dns2socks,hysteria,ipt2socks,microsocks,naiveproxy,shadowsocks-libev,shadowsocks-rust,shadowsocksr-libev,simple-obfs,tcping,trojan-plus,tuic-client,v2ray-plugin,xray-plugin,geoview,shadow-tls}
        git clone https://github.com/Openwrt-Passwall/openwrt-passwall-packages package/passwall-packages
        # 移除 openwrt feeds 过时的luci版本
        rm -rf feeds/luci/applications/luci-app-passwall
        git clone https://github.com/Openwrt-Passwall/openwrt-passwall package/passwall-luci

    - name: install
      run: cd immortalwrt-mt798x && ./scripts/feeds install -a
        
    - name: golang
      run: cd immortalwrt-mt798x && rm -rf ./feeds/packages/lang/golang && git clone --depth 1 https://github.com/sbwml/packages_lang_golang -b 25.x feeds/packages/lang/golang

    - name: 【步骤】
      run: echo "【输入q 然后cd immortalwrt-mt798x && make menuconfig 结束sudo touch /continue】"
    - name: Setup tmate session # https://github.com/mxschmitt/action-tmate https://github.com/marketplace/actions/debugging-with-ssh
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 30


    - name: config
      run: |
        cd immortalwrt-mt798x
        cp -f .config ipk.config

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: config
        path: immortalwrt-mt798x/ipk.config

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 0
