name: cdnspeedtest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - run: go version

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison \
        build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext \
        gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev \
        libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev \
        libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp \
        ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools \
        python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo \
        uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev clang g++ libncurses-dev \
        python3-distutils file devscripts debhelper libjson-c-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Download
      run: |
        git clone --depth=1 https://github.com/hanwckf/immortalwrt-mt798x.git immortalwrt-mt798x
        cd immortalwrt-mt798x
        cp -f defconfig/mt7981-ax3000.config .config
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        #find . -type d -name "cdnspeedtest"
        #./feeds/packages/net/cdnspeedtest
        #./package/cdnspeedtest
        #grep PKG_VERSION ./package/cdnspeedtest/Makefile
        rm -rf ./feeds/packages/net/cdnspeedtest
        mkdir -p "package/cdnspeedtest"
        curl -fL "https://raw.githubusercontent.com/immortalwrt/packages/master/net/cdnspeedtest/Makefile" | sed 's,../../lang,$(TOPDIR)/feeds/packages/lang,' > "package/cdnspeedtest/Makefile"
        sed -i 's|^PKG_VERSION:=.*|PKG_VERSION:=2.3.4|' package/cdnspeedtest/Makefile
        sed -i 's|^PKG_HASH:=.*|PKG_HASH:=2003440cc264b213eed55bd64939d2b270fd02b1f008d2b721debf01a88f4cb8|' package/cdnspeedtest/Makefile
        #./scripts/feeds install golang cdnspeedtest

    - name: cdnspeedtest
      run: |
        cd immortalwrt-mt798x
        \cp -f $GITHUB_WORKSPACE/config/cdnspeedtest.config .config
        make defconfig
        make toolchain/install V=s
        make target/compile V=s
        make package/cdnspeedtest/compile V=s

    - name: ipk
      run: |
        cd immortalwrt-mt798x
        find ./staging_dir/ -name 'ld-musl-*.so*'
        find ./ -type d -name '*cdnspeedtest*'
        find ./ -type f -name '*cdnspeedtest*.ipk'

    - name: Locate cdnspeedtest .ipk
      run: |
        mkdir -p ipk-out
        find ./ -type f -name 'cdnspeedtest*.ipk' -exec cp {} ipk-out/ \;

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ipk
        path: ipk-out/

#    - name: 【步骤】
#      run: echo "【输入q 然后cd immortalwrt-mt798x && make menuconfig 结束sudo touch /continue】"
#    - name: Setup tmate session # https://github.com/mxschmitt/action-tmate https://github.com/marketplace/actions/debugging-with-ssh
#      uses: mxschmitt/action-tmate@v3
#      timeout-minutes: 30

#    - name: config
#      run: |
#        cd immortalwrt-mt798x
#        cp -f .config cdnspeedtest.config

#    - name: Upload artifact
#      uses: actions/upload-artifact@v4
#      with:
#        name: config
#        path: immortalwrt-mt798x/cdnspeedtest.config

