name: menuconfig24.10

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - run: go version

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison \
        build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext \
        gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev \
        libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev \
        libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp \
        ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools \
        python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo \
        uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev clang g++ libncurses-dev \
        python3-distutils file devscripts debhelper libjson-c-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Download
      run: |
        git clone -b openwrt-24.10-6.6 https://github.com/padavanonly/immortalwrt-mt798x-6.6 immortalwrt-mt798x-6.6
        cd immortalwrt-mt798x-6.6
        echo "src-git nikki https://github.com/nikkinikki-org/OpenWrt-nikki.git;main" >> "feeds.conf.default"
        echo "src-git cdnspeedtest https://github.com/immortalwrt-collections/openwrt-cdnspeedtest.git" >> "feeds.conf.default"

        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install golang cdnspeedtest
        sed -i 's|^PKG_SOURCE:=.*|PKG_SOURCE:=master.tar.gz|' feeds/cdnspeedtest/cdnspeedtest/Makefile
        sed -i 's|^PKG_SOURCE_URL:.*|PKG_SOURCE_URL:=https://github.com/XIU2/CloudflareSpeedTest/archive/refs/heads/|' feeds/cdnspeedtest/cdnspeedtest/Makefile
        sed -i 's|^PKG_HASH:=.*|PKG_HASH:=ca067c0a1de9f90849978fdf0e06c0c259bd366eba77c73bfd2c83df0d593e03|' feeds/cdnspeedtest/cdnspeedtest/Makefile
        sed -i 's|^PKG_SOURCE:=.*|PKG_SOURCE:=master.tar.gz|' feeds/packages/net/cdnspeedtest/Makefile
        sed -i 's|^PKG_SOURCE_URL:.*|PKG_SOURCE_URL:=https://github.com/XIU2/CloudflareSpeedTest/archive/refs/heads/|' feeds/packages/net/cdnspeedtest/Makefile
        sed -i 's|^PKG_HASH:=.*|PKG_HASH:=ca067c0a1de9f90849978fdf0e06c0c259bd366eba77c73bfd2c83df0d593e03|' feeds/packages/net/cdnspeedtest/Makefile
        git clone https://github.com/xiaorouji/openwrt-passwall.git package/passwall
        git clone https://github.com/xiaorouji/openwrt-passwall-packages.git package/passwall-packages
        #git clone https://github.com/immortalwrt/packages.git immortalwrt-packages && rm -rf ./feeds/packages/lang/golang && mv ./immortalwrt-packages/lang/golang feeds/packages/lang/golang && rm -rf ./immortalwrt-packages
        cp -f defconfig/mt7981-ax3000.config .config

    - name: Setup tmate session 步骤：【输入q 命令cd immortalwrt-mt798x-6.6 && make menuconfig 结束运行sudo touch /continue】 # https://github.com/mxschmitt/action-tmate https://github.com/marketplace/actions/debugging-with-ssh
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 30

    - name: cdnspeedtest
      run: |
        cd immortalwrt-mt798x-6.6
        find ./ -type d -name '*cdnspeedtest*'
        make package/cdnspeedtest/compile V=s
        find ./ -type d -name '*cdnspeedtest*'

    - name: config
      run: |
        cd immortalwrt-mt798x-6.6
        #mv .config padavanonly.config
        cp -f .config padavanonly.config

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: config
        path: |
          immortalwrt-mt798x-6.6/padavanonly.config
          360T7/immortalwrt-mt798x-6.6/padavanonly.config
