name: menuconfig24.10

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - run: go version

    - name: Download
      run: |
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        git clone -b openwrt-24.10-6.6 --single-branch --filter=blob:none https://github.com/padavanonly/immortalwrt-mt798x-6.6 immortalwrt-mt798x-24.10
        cd immortalwrt-mt798x-24.10
        git clone https://github.com/xiaorouji/openwrt-passwall.git package/passwall
        git clone https://github.com/xiaorouji/openwrt-passwall-packages.git package/passwall-packages
        echo "src-git nikki https://github.com/nikkinikki-org/OpenWrt-nikki.git;main" >> "feeds.conf.default"
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        cp -f defconfig/mt7981-ax3000.config .config

    - name: 【步骤】
      run: echo "【输入q 然后cd immortalwrt-mt798x-24.10 && make menuconfig 结束sudo touch /continue】"

    - name: Setup tmate session # https://github.com/mxschmitt/action-tmate https://github.com/marketplace/actions/debugging-with-ssh
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 30

    - name: config
      run: |
        cd immortalwrt-mt798x-24.10
        cp -f .config padavanonly.config

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: config
        path: |
          immortalwrt-mt798x-24.10/padavanonly.config

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 0
